name: Deploy to Cloud Run

on:
  push:
    tags:
      - 'v*'
      
jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: celestial-geode-464418-p8

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy image-service-development \
            --project=celestial-geode-464418-p8 \
            --source . \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --update-env-vars FIREBASE_BUCKET=celestial-geode-464418-p8.appspot.com
