name: Deploy to Cloud Run on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create firebase-service-account.json
        run: echo "${{ secrets.GCP_SA_KEY }}" > firebase-service-account.json

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-service

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy image-service-development \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-service \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated